### ISSUE TITLE
Where do you get the username/password?

### ISSUE THREAD

**Issue by ghost** [tejado/pokemongo-api-demo#1]
/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    main()
  File "main.py", line 107, in main
    access_token= login_pokemon('yourusername','yourpass')
  File "main.py", line 95, in login_pokemon
    ticket=re.sub('.*ticket=','',r1.history[0].headers['Location'])
IndexError: list index out of range

**Comment by pogoman3** [comment]
It's a PTC password that's hard-coded.

**Comment by rpmry** [comment]
where can i get one?

**Comment by tejado** [comment]
It is the Pokemon Trainer Club. You can register an account inside the game.
Do you need google support?

**Comment by rpmry** [comment]
@tejado @pogoman3 is it possible with gmail accounts?

**Comment by tejado** [comment]
not yet
