### ISSUE TITLE
FORT_DETAILS

### ISSUE THREAD

**Issue by larsschwarz** [tejado/pokemongo-api-demo#104]
How would adding FORT_DETAILS work? I was expecting it takes the fort id, but since it does not expects a parameter I'm assuming I have to set the position first and just call FORT_DETAILS? It's different from the process in the game, because you can click any nearby Pokestop and get it's details. Anyone added this functionality already and can shed a light (just need the title/description and image for Stops).

**Comment by RyanJarv** [comment]
Going to be working on this as well, was using another c# api that did this but going to try to get it working in this one. The c# lib isn't online anymore but the code looks like this for the details part

```
        public async Task<FortDetailResponse> GetFort(string fortId, double fortLat, double fortLng)
        {
            var customRequest = new Request.Types.FortDetailsRequest()
            {
                Id = ByteString.CopyFromUtf8(fortId),
                Latitude = Utils.FloatAsUlong(fortLat),
                Longitude = Utils.FloatAsUlong(fortLng),
            };

            var fortDetailRequest = RequestBuilder.GetRequest(_unknownAuth, _currentLat, _currentLng, 10,
                new Request.Types.Requests()
                {
                    Type = (int)RequestType.FORT_DETAILS,
                    Message = customRequest.ToByteString()
                });
            return await _httpClient.PostProto<Request, FortDetailResponse>($"https://{_apiUrl}/rpc", fortDetailRequest);
        }
```

**Comment by RyanJarv** [comment]
Well I guess there's more then that.. I'm not good with c# anyways ping me if you want to try to figure out how to port it to this lib

Edit: looks like the cached version is here https://webcache.googleusercontent.com/search?q=cache:JeC9PRIUX2gJ:https://github.com/FeroxRev/Pokemon-Go-Rocket-API/blob/master/PokemonGo/RocketAPI/Client.cs+&cd=1&hl=en&ct=clnk&gl=us

**Comment by RyanJarv** [comment]
Hey just a follow up, this seems to work for getting the details, it's the same as the spin fort call.

```
        api.get_map_objects(latitude = util.f2i(lat), longitude = util.f2i(lng), since_timestamp_ms = timestamps, cell_id = cell_ids)
        response_dict = api.call()       
        map_objects = response_dict['responses']['GET_MAP_OBJECTS']
        for map_cell in map_objects['map_cells']:
            if not 'forts' in map_cell:
                log.debug("Didn't find any forts in this map_cell")
                continue
            for fort in map_cell['forts']:
                api.fort_details(fort_id = fort['id'], latitude = fort['latitude'], longitude = fort['longitude'])
```

**Comment by glenncampioni** [comment]
It does take arguments, as you can see in the C# code @RyanJarv posted.
This is the python call I use : 
`fort_details(fort_id=self.fort['id'],
                              latitude=lat,
                              longitude=lng)`

So the parameters are GUID, lat and long.

**Comment by vmunich** [comment]
What about getting the gym's members?

**Comment by larsschwarz** [comment]
get_gym_details returns "memberships" that include trainer name, avatar settings and pokemon data (incl. cp, num upgrades and so on). It expects player lat/lng, gym lat/lng and gym id.
