### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by miqueet** [tejado/pokemongo-api-demo#107]
pip install  git+https://github.com/tejado/pgoapi.git
Downloading/unpacking git+https://github.com/tejado/pgoapi.git
  Cloning https://github.com/tejado/pgoapi.git to /tmp/pip-pTKP8e-build
  Running setup.py egg_info for package from git+https://github.com/tejado/pgoapi.git
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/tmp/pip-pTKP8e-build/setup.py", line 9, in <module>
        install_reqs = parse_requirements(path_req, session=False)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/pip-pTKP8e-build/setup.py", line 9, in <module>

```
install_reqs = parse_requirements(path_req, session=False)
```

TypeError: parse_requirements() got an unexpected keyword argument 'session'

---

Command python setup.py egg_info failed with error code 1 in /tmp/pip-pTKP8e-build
Storing complete log in /root/.pip/pip.log

**Comment by elliottcarlson** [comment]
Try updating pip first;

`sudo pip install --upgrade pip`

**Comment by miqueet** [comment]
thanks that worked.
