### ISSUE TITLE
Add Support for Incubating Eggs

### ISSUE THREAD

**Issue by bstpierr** [tejado/pokemongo-api-demo#108]
The API should have support for assigning eggs to incubators (or the other way around depending on the RPC).

Along with with support, the API should also surface the notification that the egg has hatched.

**Comment by elliottcarlson** [comment]
See https://github.com/tejado/pgoapi/issues/86 regarding a conversation about egg incubation.

As for supporting notifications - that's not really the point of an API. The API surfaces a way to interact with the service; polling and acting on the responses is something that your end client/scripts/etc should be handling. The information you are looking for can be retrieved from a GET_HATCHED_EGGS request. This is demonstrated in the sample script: https://github.com/tejado/pgoapi/blob/d98bbf1d1f658b0c7e3e6e8ad5dd6613ab6547c4/pgoapi/pgoapi.py#L153

**Comment by bstpierr** [comment]
Thanks for the issue reference, that's essentially what I'm looking for. Regarding the notifications, of course it's not the API's job to schedule checking the hatched eggs, I mostly meant that the API should have a way to check if any eggs have hatched (which I didn't know already existed)

It appears as though the API already supports everything I was asking for. Thanks!
