### ISSUE TITLE
API returning 502

### ISSUE THREAD

**Issue by kylearmington** [tejado/pokemongo-api-demo#109]
http://i.imgur.com/17buxwJ.png

Everything was running fine all day today but stopped working 10 min ago.  
I assume it's the same for everyone.

**Comment by elliottcarlson** [comment]
Most likely slammed servers as usual. When the code doesn't change, assume it's on their side.

**Comment by tejado** [comment]
@kylearmington which bot are you using (just for interesst)?

**Comment by kylearmington** [comment]
@tejado - For interest - I'm using @timwah's pokeslack bot - it saves my office a lot of time checking their phones / pokevision.com / etc and it is just amazing.  10/10 recommend.

and yea pretty sure it was just slammed servers.
