### ISSUE TITLE
update_pokemon problem

### ISSUE THREAD

**Issue by iCyclus** [tejado/pokemongo-api-demo#118]
UpgradePokemonMessage.proto has a uint64 for the pokemon_id and i think it's wrong...
I tried multiple times to get this to work but i can't,
so im guessing it has to be fixed64?!

**Comment by iCyclus** [comment]
confirmed https://github.com/AeonLucid/POGOProtos/issues/80

**Comment by alistairmackenzie** [comment]
This was fixed in the following PR. Just waiting on someone to update this repo, I'll get on it now.

https://github.com/AeonLucid/POGOProtos/pull/56

**Comment by tejado** [comment]
I updated the protos now with commit https://github.com/tejado/pgoapi/commit/81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b
