### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by patrik7** [tejado/pokemongo-api-demo#120]
pbeck /home/pbeck/workspace/PokemonGo-Bot (master)  
sudo pip install git+https://github.com/tejado/pgoapi.git
Downloading/unpacking git+https://github.com/tejado/pgoapi.git
  Cloning https://github.com/tejado/pgoapi.git to /tmp/pip-pQ8Jzj-build
  Running setup.py egg_info for package from git+https://github.com/tejado/pgoapi.git
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/tmp/pip-pQ8Jzj-build/setup.py", line 9, in <module>
        install_reqs = parse_requirements(path_req, session=False)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/pip-pQ8Jzj-build/setup.py", line 9, in <module>

```
install_reqs = parse_requirements(path_req, session=False)
```

TypeError: parse_requirements() got an unexpected keyword argument 'session'

---

Command python setup.py egg_info failed with error code 1 in /tmp/pip-pQ8Jzj-build

**Comment by patrik7** [comment]
Version when tried: ebffcdb60815a338d8a4171f8a33577e8dccb66f

**Comment by alistairmackenzie** [comment]
Please update your pip using easy_install. This fixed similar problems for me on a new VM.

**Comment by patrik7** [comment]
What version do you have? I updated but it didn't fix the problem :/

pbeck /home/pbeck/workspace/PokemonGo-Bot (master)                              

> sudo easy_install pip

Searching for pip
Best match: pip 1.1
Adding pip 1.1 to easy-install.pth file
Installing pip-2.7 script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Processing dependencies for pip
Finished processing dependencies for pip
pbeck /home/pbeck/workspace/PokemonGo-Bot (master)                              

> sudo pip install git+https://github.com/tejado/pgoapi.git

Downloading/unpacking git+https://github.com/tejado/pgoapi.git
  Cloning https://github.com/tejado/pgoapi.git to /tmp/pip-ioZM_q-build
  Running setup.py egg_info for package from git+https://github.com/tejado/pgoapi.git
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/tmp/pip-ioZM_q-build/setup.py", line 9, in <module>
        install_reqs = parse_requirements(path_req, session=False)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/pip-ioZM_q-build/setup.py", line 9, in <module>

```
install_reqs = parse_requirements(path_req, session=False)
```

TypeError: parse_requirements() got an unexpected keyword argument 'session'

---

Command python setup.py egg_info failed with error code 1 in /tmp/pip-ioZM_q-build

**Comment by alistairmackenzie** [comment]
pip 8.1.2 is what I'm using

**Comment by patrik7** [comment]
> sudo pip install -U pip

worked on ubuntu, in case anybody gets here
