### ISSUE TITLE
Freezing PRoblems with google.protobuf library

### ISSUE THREAD

**Issue by Wegi** [tejado/pokemongo-api-demo#123]
There is an issue when trying to freeze a program (with pyinstaller, cx_freeze, etc.) that uses your library. This problem is caused by the google.protobuf module.

Does anybody have a solution for it?

**Comment by tejado** [comment]
What kind of issue? And why you assume that it is caused by google.protobuf? Do you have some error message or something like that?

**Comment by Wegi** [comment]
After freezing (disregarding the tool) this is the error message when starting the app:

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/wegi/pyinstaller_old/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 313, in load_module
    exec(bytecode, module.__dict__)
  File "/home/wegi/.virtualenvs/poke-cruncher/lib/python3.5/site-packages/pgoapi/__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3
```

This is even the case when the freezing programms get the explicit instruction to take google.protobuf into consideration.

**Comment by tejado** [comment]
PleaseInstallProtobufVersion3 is raised by pgoapi if it doesnt find the correct (or no) protobuf version. Do you have protobuf in version 3 installed or still protobuf v2? If you have installed it, try to comment my code which raises the exception and run it again.

**Comment by Wegi** [comment]
I have Version three installed. My app works fine with your API. Its only when I try to compile it into an executable that the google.protobuf seems to make problems. 

As already mentioned this happens with all Programms, regardless if i user PyInstaller, cx_freeze or py2exe.

**Comment by tejado** [comment]
Did you out commented my code which raised the exception and then tried to compile it?

**Comment by Wegi** [comment]
Yeah, curiously the same problem. I even deleted the `__pycache__` folder.

**Comment by tejado** [comment]
You commented the code in **init**.py but PleaseInstallProtobufVersion3 is still raised...? This seems to be strange...

**Comment by Wegi** [comment]
The problem indeed were those two lines. Someone pointed out the correct way of freezing your library here: https://www.reddit.com/r/Python/comments/4utgwv/scripts_as_pyinstaller_cx_freeze_and_py2exe_all/ 

Thanks for your time.

**Comment by tejado** [comment]
Great :)
