### ISSUE TITLE
api.recycle_inventory_item question

### ISSUE THREAD

**Issue by Vigerus** [tejado/pokemongo-api-demo#125]
When i tried to use api.recycle_inventory_item i was expecting it to have at least two parameters: item_id, amount.

Does anyone know how to provide these data to the request?

Thanks a lot in Advance!

**Comment by tejado** [comment]
Yes, https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Requests/Messages/RecycleInventoryItemMessage.proto

```
message RecycleInventoryItemMessage {
    .POGOProtos.Inventory.Item.ItemId item_id = 1;
    int32 count = 2;
}
```

so item_id and count are the parameter names :)

**Comment by Vigerus** [comment]
well, a test call api.recycle_inventory_item(1,1) raises an exception: 

TypeError('function() takes exactly 0 arguments (2 given)',)

Sorry, but I'm a C/C++ for 20 years already, and a python rookie :)

P.S.
Your response times and a will to help are astonishing man, thanks! :)

**Comment by tejado** [comment]
try it like the examples in pokecli.py :)

```
api.recycle_inventory_item(item_id = 1, count = 1)
```

**Comment by Vigerus** [comment]
Allright! Now i get it! Thanks a lot! :)

+1 to Your Awesomeness

**Comment by nequito** [comment]
How can i filter the inventory list in order to get the count of an specific ItemID, i've tried this, but doesn't work
`    inventory_items = api.get_inventory()

```
for Item in inventory_items['Item']:

    print 'ONE ITEM!!!!!!!!!!!!'`
```

**Comment by tejado** [comment]
print the response object and see how it is structured.
