### ISSUE TITLE
No handlers could be found for logger "pgoapi.rpc_api" 

### ISSUE THREAD

**Issue by Cl0v1s** [tejado/pokemongo-api-demo#129]
Hi, 

It's probably my fault, but when I try to connect to the same account two times in the same time, I got this: 

```
[error] No handlers could be found for logger "pgoapi.rpc_api"
```

Do you know how to avoid it ? :/

**Comment by tejado** [comment]
Do you initiate the logging, e.g. https://github.com/tejado/pgoapi/blob/master/pokecli.py#L86 ?

**Comment by Cl0v1s** [comment]
Huuuuuuuh forgot this part ! Thanks a lot ! :D

**Comment by tejado** [comment]
But I will set a null handler for all internal modules in the next fix, just for safety reasons ;)

**Comment by davey-dev** [comment]
It's because login is slammed right now.
