### ISSUE TITLE
cant install protobuf3

### ISSUE THREAD

**Issue by panjitianda** [tejado/pokemongo-api-demo#132]
when access pyton web.py
gettin
`Traceback (most recent call last):
  File "web.py", line 8, in <module>
    from pgoapi.poke_utils import *
  File "/var/www/test/poketrainer/pgoapi/__init__.py", line 16, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3`

when try to install it 

Installing collected packages: protobuf
  Found existing installation: protobuf 2.6.1
    Can't uninstall 'protobuf'. No files were found to uninstall.
Successfully installed protobuf

any info?

**Comment by tejado** [comment]
How do you install it? pip install -r requirements.txt ?

**Comment by Nostrademous** [comment]
are you on OSX?

**Comment by ProLoDs** [comment]
try `https://github.com/google/protobuf/` 
or just `sudo pip install protobuf --upgrade`

**Comment by tejado** [comment]
@panjitianda status?

**Comment by dnsBlah** [comment]
pip uninstall protobuf
pip install protobuf==3.0.0b

**Comment by scottie** [comment]
apt-get install python-protobuf
