### ISSUE TITLE
map_objects returns status_code 52

### ISSUE THREAD

**Issue by ArtemBernatskyy** [tejado/pokemongo-api-demo#137]
Argument longtitude with value 4629291827860676700 unknown inside GetMapObjectsMessage (Exception: 'GetMapObjectsMessage' object has no attribute 'longtitude') and it failes with this error.

**Comment by dnsBlah** [comment]
map_objects gave status_code 52 ?

**Comment by ArtemBernatskyy** [comment]
Login type 'ptc' , yes it gives me response_dict with this
`{'responses': {}, 'status_code': 52}`

**Comment by elicwhite** [comment]
https://www.reddit.com/r/pokemongodev/comments/4v3twy/request_throttling/

**Comment by ArtemBernatskyy** [comment]
time.sleep(0.2) we need to sleep 0.2 s between requests. Plz add this to docs.
