### ISSUE TITLE
find_poi() returns status_code=52 with empty response

### ISSUE THREAD

**Issue by zero3nna** [tejado/pokemongo-api-demo#140]
The spiral_poi_search.py isnt working.
In `def find_poi(api, coords):`
returns `{'status_code': 52, 'responses': {}}`
`for coord in coords`
so `if 'status' in response_dict['responses']['GET_MAP_OBJECTS']:` fails with `KeyError: 'GET_MAP_OBJECTS'`

I fixed this by checking for an empty response: `if (response_dict['responses']):`
but I'm wondering what status_code= 52 might be..?
created a pull request also.

**Comment by tejado** [comment]
52 seems to be server throttling. I have already implemented an exception for it (will be pushed soon)

**Comment by zero3nna** [comment]
that would make sense. ok, I close this issue then
