### ISSUE TITLE
spiral_poi_search.py: KeyError: 'spawn_point_id'

### ISSUE THREAD

**Issue by larsschwarz** [tejado/pokemongo-api-demo#143]
When running the latest spiral_poi_search.py it returns following key error:

```
Traceback (most recent call last):
  File "spiral_poi_search.py", line 233, in <module>
    main()
  File "spiral_poi_search.py", line 162, in main
    find_poi(api, position[0], position[1])
  File "spiral_poi_search.py", line 188, in find_poi
    pokekey = get_key_from_pokemon(pokemon)
  File "spiral_poi_search.py", line 200, in get_key_from_pokemon
    return '{}-{}'.format(pokemon['spawn_point_id'], pokemon['pokemon_data']['pokemon_id'])
KeyError: 'spawn_point_id'
```

**Comment by davegallant** [comment]
A lot of these KeyErrors are just because the servers are semi-slammed.

**Comment by larsschwarz** [comment]
Thanks, that's what I thought, but in this case it seems the GET_MAP_OBJECTS response is complete (incl. spawn points, forts and so on)?

**Comment by Zero3nna** [comment]
spawnpoint_id was renamed in spawn_point_id ... I already submitted a pull request which got merged into the latest master version

**Comment by larsschwarz** [comment]
Thanks! That fixes this issue.
