### ISSUE TITLE
Is there a method to access the Journal?

### ISSUE THREAD

**Issue by jlevente** [tejado/pokemongo-api-demo#145]
Hey, is there a method for accessing the Journal? If so, are you going to implement it here?

**Comment by dnsBlah** [comment]
there is some log proto in the POGOProtos available.
Data/Logs/ActionLogEntry_pb2
Data/Logs/CatchPokemonLogEntry_pb2
Data/Logs/FortSearchLogEntry_pb2

Not done anything with it yet.. Maybe a other developer did ?

**Comment by tejado** [comment]
Already implemented: https://github.com/tejado/pgoapi/wiki/sfida_action_log
