### ISSUE TITLE
argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by modrzew** [tejado/pokemongo-api-demo#151]
``` pytb
Traceback (most recent call last
  File "worker.py", line 119, in run
    self.main()
  File "worker.py", line 156, in main
    cell_id=cell_ids
  File "/usr/home/modrzew/.virtualenvs/pkmn/src/pgoapi/pgoapi/pgoapi.py", line 84, in function
    return request.call()
  File "/usr/home/modrzew/.virtualenvs/pkmn/src/pgoapi/pgoapi/pgoapi.py", line 182, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position()
  File "/usr/home/modrzew/.virtualenvs/pkmn/src/pgoapi/pgoapi/rpc_api.py", line 108, in request
    if ('auth_ticket' in response_dict) and ('expire_timestamp_ms' in response_dict['auth_ticket']) and (
TypeError: argument of type 'bool' is not iterable
```

Got it when called [`PGoApi.get_map_objects`](https://github.com/modrzew/pokeminer/blob/optimization/worker.py#L153). Using 2440a56e50b5043712b4417457e1721124a26a4d.

**Comment by Nostrademous** [comment]
yes, response_dict is empty when that gets hit... I guess we didn't get a new ticket for a new session... I think you have to request it....

I always dealt with it by restarting session when i detect this event....

**Comment by tejado** [comment]
Yeah thanks. Will fix this tomorrow.

**Comment by beeradmoore** [comment]
I don't think it is a bug, I think it may be due to this, https://github.com/tejado/pgoapi/issues/156 current code works fine on local machine, remote AWS machine gets this error and displays same warning as #156

**Comment by modrzew** [comment]
I'm not using AWS, and my server's IP certainly hasn't been blocked, as I'm getting it only occasionally.

**Comment by Cl0v1s** [comment]
It appears they blocked OpenShift. I dealed with it by adding a proxy. 

in rpc_api.py constructor:

```
        self._session = requests.session()
        self._session.headers.update({'User-Agent': 'Niantic App'})
        self._session.verify = True

        self.proxies = {
            'http': 'http://107.151.142.117:80',
            'https': 'http://146.148.69.50:80',
        }

```

in rpc_api.py, _make_rpc:

```
    def _make_rpc(self, endpoint, request_proto_plain):
        self.log.debug('Execution of RPC')

        request_proto_serialized = request_proto_plain.SerializeToString()
        try:
            http_response = self._session.post(endpoint, data=request_proto_serialized, proxies=self.proxies)
        except requests.exceptions.ConnectionError as e:
            raise ServerBusyOrOfflineException

        return http_response
```

Just have to find a faster proxy.

**Comment by tejado** [comment]
TypeError: argument of type 'bool' is not iterable error is now fixed.
Also added an exception for the 403 stuff. Please check :)
