### ISSUE TITLE
[rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403

### ISSUE THREAD

**Issue by Otokiru** [tejado/pokemongo-api-demo#156]
403 = forbidden... Did Niantic just blocked the API or their server is just down?

**Comment by aaiezza** [comment]
Most likely

**Comment by Otokiru** [comment]
Looks like Niantic mass ban AWS IPs

**Comment by beeradmoore** [comment]
Yep, ran same script from AWS and from desktop. Desktop worked fine. AWS failed.

**Comment by jtdroste** [comment]
This should be closed.

Looks like niantic is finally blocking cloud providers IPs.

**Comment by trickpattyFH20** [comment]
hmmm.... what are some cloud services that nobody uses... random obscure VPS in Russia maybe? oh I know! google cloud! Kappa
