### ISSUE TITLE
using items issue

### ISSUE THREAD

**Issue by dnsBlah** [tejado/pokemongo-api-demo#166]
For using Raspberries or Catching pokemons I'm finding a lot of issues
responses with status_code 3 etc
even with a delay of 10 seconds, i still get this status_code

Anyone knows this issue

**Comment by Nostrademous** [comment]
I do not have this issue... it has to be that you are using wrong proto or supplying incorrect arguments

I use this for RazzBerry (eid comes from GetIncensePokemonReponse.encounter_id or MapPokemon.encounter_id or fort.lure_info.encounter_id - depending on which pokemon i'm catching), spawn_point_guid is similar.:
`self.api.use_item_capture(item_id=701, encounter_id=eid, spawn_point_guid=espawn)`

proto is:

```
message UseItemCaptureRequest {                                                                                                              |                            name = self.nameOfPokemonById(enc_resp.pokemon_data.pokemon_id - 1)
  optional RpcEnum.ItemId item_id = 1;                                                                                                       |                            number = int(self.pokemons[enc_resp.pokemon_data.pokemon_id-1]['Number'])
  optional fixed64 encounter_id = 2;                                                                                                         |                            xp += self.prepToThrowBall(enc_resp.pokemon_data.cp, name, number, fort.lure_info.encounter_id, fort.lure_info.f
  optional string spawn_point_guid = 3;                                                                                                      |ort_id)
} 
```

**Comment by dnsBlah** [comment]
woops typo, I'm really sorry -_-
