### ISSUE TITLE
get_map_objects does not contain forts

### ISSUE THREAD

**Issue by freemanovec** [tejado/pokemongo-api-demo#167]
Hi! I used a previous version of this API where get_map_objects call had forts (and generally more info) in the response dictionary, but now it contains just a timestamp and some s2_cell_id.
How do I get the forts in given cell in this new version?

**Comment by dnsBlah** [comment]
put a time.sleep(5) before your call

**Comment by freemanovec** [comment]
Still nothing, just:
`{
    "request_id": 23041360407064180, 
    "responses": {
        "GET_MAP_OBJECTS": {
            "map_cells": [
                {
                    "current_timestamp_ms": 1470157163772, 
                    "s2_cell_id": 1152921501385621504
                }, 
                {
                    "current_timestamp_ms": 1470157163772, 
                    "s2_cell_id": 1152921503533105152
                }
            ], 
            "status": 1
        }
    }, 
    "status_code": 1
}
`
Call:
`sleep(5)
req = self.api.create_request()
req.get_map_objects(latitude=f2i(lat),
                    longitude=f2i(lng),
                    since_timestamp_ms=timestamp,
                    cell_id=cellid)
response_dict = req.call()`

**Comment by freemanovec** [comment]
And none of the param's methods performs any call

**Comment by freemanovec** [comment]
And I've tried the same thing using the old version and it worked, so I don't think it's a server-side check.

**Comment by freemanovec** [comment]
Propably just a problem with location, so I'm passing it ZERO lon & lng
