### ISSUE TITLE
Encounter Status 3, empty ENCOUNTER

### ISSUE THREAD

**Issue by freemanovec** [tejado/pokemongo-api-demo#169]
Hi! I'm trying to get the encounter response, but it always returns me status_code 3 with empty ENCOUNTER. 
I tried passing it both float lat&lng in degrees with decimals and i2f from those values. Both gave 3.
It isn't softban issue, I tried it on two accounts

**Comment by dnsBlah** [comment]
I'm having this on multiple proto calls.
In my case not on encounter, but on useItemCapture, catchPokemon, getMapObjects

It's completely random, then it will just go on, after a few retries or eventually a re-login
really annoying

**Comment by freemanovec** [comment]
Nope, it's definitely because of the new API version. It changed the format in which it requires location and I'm really pissed of because it's not documented. I tried f2i (e.g. 14.145), I even created a reversal function (e.g. 4632252026721483547), but I'm still getting status 3. Anything would be really appreciated, all responses, all links, every other issue link etc.

**Comment by dnsBlah** [comment]
to be honest
the old api seems not to have this problem indeed
its since the new proto aproach

**Comment by dnsBlah** [comment]
sorry for new post
cant edit on my iphone

i do find this issue since the last update(s) of the game

**Comment by freemanovec** [comment]
Well there must be some working implementations of pokemon catching using this API, we could dig the data from there.

**Comment by dnsBlah** [comment]
For me it's working at least for 95% :s

**Comment by freemanovec** [comment]
In what format are you giving it all the arguments + can you please provide an example? It would surely help a lot

**Comment by Nostrademous** [comment]
Are you talking about Incense Encounters or ???

**Comment by freemanovec** [comment]
Wild pokemons encounters. Those that are in get_map_objects

**Comment by freemanovec** [comment]
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/
