### ISSUE TITLE
Where to put: api = pgoapi.PGoApi() api.set_position(40...?

### ISSUE THREAD

**Issue by ankerbachryhl** [tejado/pokemongo-api-demo#172]

**Comment by tejado** [comment]
?

**Comment by ankerbachryhl** [comment]
@tejado "Before any API requests can be executed, it is necessary to set a position and then to login. The coordinates are latitude, longitude and altitude. For the login, it is possible to use "google" so your google account or "ptc" (Pokemon Trainer Club).

api = pgoapi.PGoApi()
api.set_position(40.7127837, -74.005941, 0.0)
api.login('ptc', 'your_username', 'your_secure_password')
api.login will of course return True or False."

This text is from the wiki, I just don't understand where I should put: api = pgoapi.PGoApi()
api.set_position(40.7127837, -74.005941, 0.0)
api.login('ptc', 'your_username', 'your_secure_password') :(

**Comment by elliottcarlson** [comment]
That would be within your python script -- is your intention to write your own interface to the API, or are you looking for something pre-built?

**Comment by ankerbachryhl** [comment]
I think I'm gonna write my own interface @elliottcarlson  :) Why? And which python script? pgoapi.py?

**Comment by tejado** [comment]
THe python script you are writing. pgoapi is a library/module/package not an application. So use the pokecli.py example or start from sratch...

**Comment by ankerbachryhl** [comment]
Ahhhh okay @tejado Thank you for the awesome api :) 👍
