### ISSUE TITLE
Calculating Cap radius/height

### ISSUE THREAD

**Issue by nborrmann** [tejado/pokemongo-api-demo#173]
In `utilities.py/get_cell_ids()` you're creating a `s2sphere.Cap`. The constructor accepts a position and the height of the cap (see the s2sphere documentation). For the height, you're inputting 

```
Angle.from_degrees(360*radius/(2*math.pi*EARTH_RADIUS))
```

I don't understand what this is supposed to do (just looking at the units it doesn't make sense ... you have a distance (radius) and treat it like an angle?). I suggest calculating the height from the radius as `1-cos(asin(radius/earth_radius))`. (I have tested this and it returns good results)

**Comment by poemdexter** [comment]
You're looking at Cap.from_axis_height and not Cap.from_axis_angle documentation.

**Comment by nborrmann** [comment]
yes youre right
