### ISSUE TITLE
Don't utilise Google geocode when parsed location is lat/lng

### ISSUE THREAD

**Issue by larsschwarz** [tejado/pokemongo-api-demo#178]
I'm often running into geolocator rate limiting, because the the get_pos_by_name tries to decode a given lat/lng position instead of just returning the parsed lat/lng. Even pokecli.py isn't actually part of the API itself it would be nice to skip geocoding in those cases.

**Comment by NaderCHASER** [comment]
This was already fixed in commit 9363c190477263a04be40bde7ebf910b78fc08bb

**Comment by larsschwarz** [comment]
Sorry, did not notice I'm behind - commit-wise.
