### ISSUE TITLE
Repeated notifications

### ISSUE THREAD

**Issue by ffsd** [tejado/pokemongo-api-demo#194]
I can see and hear notifications for selected pokemons but they keep repeating for the same pokemon and it unbarable to keep the map open. It happens in **every browser.**
This is an issue that **already ocurred** on **previous version**s.
How can I **just** receive the notification **once**? 

Is there anything I can change in the map file provided?

<h3>Notification Settings</h3>

```
      <div>
        <div class="form-control">
          <label for="notify-pokemon">
            <h3>Notify of Pokémon</h3>
            <div style="max-height:165px;overflow-y:auto";>
              <select id="notify-pokemon" multiple="multiple"></select>
            </div>
          </label>
        </div>
        <div class="form-control switch-container">
          <h3>Notify with sound</h3>
          <div class="onoffswitch">
            <input id="sound-switch" type="checkbox" name="sound-switch" class="onoffswitch-checkbox" checked>
            <label class="onoffswitch-label" for="sound-switch">
            <span class="switch-label" data-on="On" data-off="Off"></span>
```

**Comment by ffsd** [comment]
Its the multiple ="multiple isn´t it? Is that so obvious... I'll try it

**Comment by ProLoDs** [comment]
this is the api git, no  idea what html is doing here...
