### ISSUE TITLE
what is cell_id and since_timestamp_ms

### ISSUE THREAD

**Issue by ghost** [tejado/pokemongo-api-demo#198]
For the function get_map_objects() I have no clue how to plug in the first two arguments or how to get them. Can anyone help?

**Comment by Vigerus** [comment]
pokecli.py is your friend, there's an example:

# print get maps object

cell_ids = util.get_cell_ids(position[0], position[1])
timestamps = [0,] \* len(cell_ids)
response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
print('Response dictionary (get_player): \n\r{}'.format(pprint.PrettyPrinter(indent=4).pformat(response_dict)))

**Comment by tomgie** [comment]
I guess get_map_objects() was not as I expected, is there anything that shows where pokemon are or their location within the area or is there just none that I can see in the json?

**Comment by tomgie** [comment]
@Vigerus The json I am getting from the request only shows s2_cell_id and current_timestamp_ms. No pokemon/gyms

**Comment by tomgie** [comment]
close

**Comment by Moosheplusplus** [comment]
@tomgie you can close the issue yourself by clicking "Comment and close", or just "Close".
