### ISSUE TITLE
So this doesnt' do antyhgin yet?

### ISSUE THREAD

**Issue by rpmry** [tejado/pokemongo-api-demo#2]
I can't add starduszt or pokecoins

**Comment by marcomarotta** [comment]
Lol... Don't know if trolling or what... At this point you can barely auth and you want a free (server side) the hack? You deserve to get scammed by the programs who promise you hack the game so

**Comment by MelonSmasher** [comment]
Trollz

**Comment by DerScreever** [comment]
maybe close this? 
this is just useless issue
