### ISSUE TITLE
Pokemon Bot

### ISSUE THREAD

**Issue by kkatayama** [tejado/pokemongo-api-demo#20]
I have logged in using your tool. How do I load the Pokestop bot?

**Comment by Elyx0** [comment]
You don't. As it's not available publicly yet.

**Comment by Simon0x** [comment]
For the pokestop bot use this https://github.com/Mila432/Pokemon_Go_API

~Request for Close

**Comment by tejado** [comment]
Afaik, Mila has no bot code published.
