### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by EvolvedPie** [tejado/pokemongo-api-demo#217]
Not sure what is going wrong.  The command I'm using to launch is:
python pokecli.py -a ptc -u **\* -p **\* -l "_**"
With the correct information not *_\* of course.  But I can work out why the server isn't starting, by which I mean the map.
I have copied my console output below replacing logins and location with **\* (I hope)
Any advice as to why this is not working would be greatly appreciated.

Many thanks!

2016-08-13 17:26:38,052 [    pgoapi] [ INFO] pgoapi v1.1.6 - Copyright (c) 2016 tjado https://github.com/tejado
2016-08-13 17:26:38,532 [ utilities] [ INFO] Location for '_**' found: *_*
2016-08-13 17:26:38,532 [ utilities] [ INFO] Coordinates (lat/long/alt) for location: ***
2016-08-13 17:26:38,532 [  auth_ptc] [ INFO] Login for: ***
2016-08-13 17:26:39,224 [  auth_ptc] [ INFO] PTC Login successful
2016-08-13 17:26:39,224 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-08-13 17:26:39,224 [    pgoapi] [ INFO] Creating a new request...
2016-08-13 17:26:39,224 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-08-13 17:26:39,224 [    pgoapi] [ INFO] Adding 'GET_HATCHED_EGGS' to RPC request
2016-08-13 17:26:39,224 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-08-13 17:26:39,224 [    pgoapi] [ INFO] Adding 'CHECK_AWARDED_BADGES' to RPC request
2016-08-13 17:26:39,224 [    pgoapi] [ INFO] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
2016-08-13 17:26:39,224 [    pgoapi] [ INFO] Execution of RPC
2016-08-13 17:26:39,693 [    pgoapi] [ INFO] Cleanup of request!
2016-08-13 17:26:39,694 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
2016-08-13 17:26:39,694 [    pgoapi] [ INFO] Login process completed
2016-08-13 17:26:39,694 [    pgoapi] [ INFO] Creating a new direct request...
2016-08-13 17:26:39,694 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-08-13 17:26:39,694 [    pgoapi] [ INFO] Execution of RPC
2016-08-13 17:26:39,953 [    pgoapi] [ INFO] Cleanup of request!
2016-08-13 17:26:40,960 [    pgoapi] [ INFO] Creating a new request...
2016-08-13 17:26:40,960 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-08-13 17:26:40,960 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-08-13 17:26:40,960 [    pgoapi] [ INFO] Execution of RPC
2016-08-13 17:26:41,171 [    pgoapi] [ INFO] Cleanup of request!
Response dictionary (get_player):
{   'api_url': u'pgorelease.nianticlabs.com/plfe/628',
    'request_id': 563059720150564162L,
    'responses': {   'GET_PLAYER': {   'player_data': {   'avatar': {   },
                                                          'contact_settings': {   },
                                                          'creation_timestamp_ms': 1470343187315L,
                                                          'currencies': [   {   'name': u'POKECOIN'},
                                                                            {   'amount': 100,
                                                                                'name': u'STARDUST'}],
                                                          'daily_bonus': {   },
                                                          'equipped_badge': {   },
                                                          'max_item_storage': 350,
                                                          'max_pokemon_storage': 250,
                                                          'tutorial_state': [   0,
                                                                                1,
                                                                                3,
                                                                                4,
                                                                                7],
                                                          'username': u'**_'},
                                       'success': True}},
    'status_code': 2}
Response dictionary (get_player + get_inventory):
{   'request_id': 563059720150564163L,
    'responses': {   'GET_INVENTORY': {   'inventory_delta': {   'inventory_items': [   {   'inventory_item_data': {   'item': {   'count': 50,
                                                                                                                                   'item_id': 1,
                                                                                                                                   'unseen': True}}},
                                                                                        {   'inventory_item_data': {   'player_stats': {   'experience': 600L,
                                                                                                                                           'level': 1,
                                                                                                                                           'next_level_xp': 1000L,
                                                                                                                                           'pokemons_captured': 1,
                                                                                                                                           'pokemons_encountered': 1,
                                                                                                                                           'unique_pokedex_entries': 1}}},
                                                                                        {   'inventory_item_data': {   'candy': {   'candy': 3,
                                                                                                                                    'family_id': 1}}},
                                                                                        {   'inventory_item_data': {   'egg_incubators': {   'egg_incubator': [   {   'id': u'EggIncubatorProto781372583315601689',
                                                                                                                                                                      'incubator_type': 1,
                                                                                                                                                                      'item_id': 901}]}}},
                                                                                        {   'inventory_item_data': {   'pokedex_entry': {   'pokemon_id': 1,
                                                                                                                                            'times_captured': 1,
                                                                                                                                            'times_encountered': 1}}},
                                                                                        {   'inventory_item_data': {   'item': {   'count': 2,
                                                                                                                                   'item_id': 401,
                                                                                                                                   'unseen': True}}},
                                                                                        {   'inventory_item_data': {   'item': {   'count': 1,
                                                                                                                                   'item_id': 901,
                                                                                                                                   'unseen': True}}},
                                                                                        {   'inventory_item_data': {   'pokemon_data': {   'captured_cell_id': 5220095777492172800L,
                                                                                                                                           'cp': 14,
                                                                                                                                           'cp_multiplier': 0.09399999678134918,
                                                                                                                                           'creation_time_ms': 1470344545399L,
                                                                                                                                           'height_m': 0.8820805549621582,
                                                                                                                                           'id': 2157526244132586669L,
                                                                                                                                           'individual_attack': 10,
                                                                                                                                           'individual_defense': 10,
                                                                                                                                           'individual_stamina': 10,
                                                                                                                                           'move_1': 221,
                                                                                                                                           'move_2': 118,
                                                                                                                                           'pokemon_id': 1,
                                                                                                                                           'stamina': 10,
                                                                                                                                           'stamina_max': 10,
                                                                                                                                           'weight_kg': 11.615195274353027}}}],
                                                                 'new_timestamp_ms': 1471105598486L},
                                          'success': True},
                     'GET_PLAYER': {   'player_data': {   'avatar': {   },
                                                          'contact_settings': {   },
                                                          'creation_timestamp_ms': 1470343187315L,
                                                          'currencies': [   {   'name': u'POKECOIN'},
                                                                            {   'amount': 100,
                                                                                'name': u'STARDUST'}],
                                                          'daily_bonus': {   },
                                                          'equipped_badge': {   },
                                                          'max_item_storage': 350,
                                                          'max_pokemon_storage': 250,
                                                          'tutorial_state': [   0,
                                                                                1,
                                                                                3,
                                                                                4,
                                                                                7],
                                                          'username': u'**_'},
                                       'success': True}},
    'status_code': 1}

**Comment by dnsBlah** [comment]
sorry, why.. but whyyy do you think this is a map?

**Comment by EvolvedPie** [comment]
Well, now that you've pointed it out it very clearly isn't.
I'm not entirely sure how to set the map up.  I'm trying to work through the instruction.
Simply put, I followed the steps in the video tutorial and it gives the impression that this should be a map.

**Comment by dnsBlah** [comment]
Just for your info, I know you closed this
This is an api it's not a full bot or anything
A lot of bots and also maps are based on this API
You must end up here by a wrong url
