### ISSUE TITLE
Status code: 3

### ISSUE THREAD

**Issue by hypixus** [tejado/pokemongo-api-demo#221]
Hello

For about two days I'm using this project python 3 interpretation by @keyphact as part of my python pokemon go inventory application, and for about 2 hours I get followingresponse when calling getInventory():
`
{
    'request_id': xxx,
    'status_code': 3,
    'unknown6':
    [{
        'unknown2':
        {
            'unknown1': 1
        },
        'response_type': 6
    }],
    'responses':
    {
        'GET_INVENTORY': {}
    },
    'auth_ticket':
    {
        'end': xxx,
        'expire_timestamp_ms': xxx,
        'start': xxx
    }
}
`
The intresting thing is, the status code changed from 1 to 3, and response is empty, not even sth like "success" = "no" Can someone explain me what it means? And most important, is it a signal i got banned or something?

**Comment by net8q** [comment]
it is probably a permaban

**Comment by dnsBlah** [comment]
I you do get reply on GET_PLAYER
yes your permabannes

**Comment by Kaankehh** [comment]
The Status Code 3 means indeed a permaban.

**Comment by dnsBlah** [comment]
just to be clear
status_code: 3

is not simply: ban

most common is a invalid request
however, it's also when you have a ban.

It's not directly a ban, its a ban on that 'request' i.e. pokemons ban, pokestops ban
(on thousands of requests within X hours)

Or in my case its on inventory,stats etc
cus of the actual permanent ban.
Just like hypixus

**Comment by dnsBlah** [comment]
I even believe they just delete your inventory...
As I can login, and get_player without problems...

**Comment by Dracon23** [comment]
If you get banned, all your requests are invalid, but if you get invalid requests, you're not banned per se... (I've been fighting with an issue that I could NOT quite wrap my head around today for a while... causing my code to get responses with status 3... while everything else worked fine <.<)

**Comment by dnsBlah** [comment]
there are partial bans as wells.That only occur on getmapobjects,catchpokemon,searchfort
as far as I know now.

But.. you will find out few hours after or the next day that the whole account got banned :)

**Comment by Dracon23** [comment]
@dnsBlah: I figured out later on that I was sending an empty cell list, which would be invalid per se ;P

**Comment by hypixus** [comment]
@dns_blah 
+rep explaining the problem
I get a full response on get_player, so it's dead end?
Also, I've made new account, but it can't do get_map_objects, response is almost the same as here...
Has not approving my account email something to it? I mean, it has a few hours, but still...

**Comment by hypixus** [comment]
update: On old account response don't even contain auth ticket, so I guess i can say gg to it. On new get_map_objects still empty response.

**Comment by hypixus** [comment]
@dnsBlah update: On old account response don't even contain auth ticket, so I guess i can say gg to it. On new get_map_objects still empty response.

**Comment by dnsBlah** [comment]
There seem to be different 'hard bans' indeed.
Some of my botted accounts cant login at all,
some only get response on get_player
some even find a fort (no pokemons) but get status_code 3 on set position etc...

Im going to start from scrath any day now. just finishing up complete randomness in ALL calls
Will first play a bit on mobile
login on other
login with bot
login again on mobile
untill i have to verify email

maybe that will be something as well ;)
