### ISSUE TITLE
CATCH_POKEMON gives status code 3

### ISSUE THREAD

**Issue by hypixus** [tejado/pokemongo-api-demo#227]
`
api.catch_pokemon(encounter_id=curpoke['encounter_id'], pokeball=1, spawn_point_id=curpoke['spawn_point_id'], hit_pokemon=True, spin_modifier=1.0, normalized_hit_position=1, normalized_reticle_size=1.8)
`
effect:
'
{'responses': {'CATCH_POKEMON': {}}, 'unknown6': [{'unknown2': {'unknown1': 1}, 'response_type': 6}], 'request_id': xxx, 'status_code': 3}
'
This happens each time on my fresh account, no matter if i catch wild_pokemons or catchable_pokemons.
Help!
@dns_blah maybe this is somehow connected with my previous problem?

**Comment by hypixus** [comment]
typo: @dnsBlah Maybe this is somehow related to my previous problems?

**Comment by dnsBlah** [comment]
are you sure you still have normal pokeballs?
did you already catched pokemons?
do you have a delay between your requests?

You don't get a reply at all.. I mean.. CATCH_POKEMON is empty, there is no result

Did you use the latest Proto for catch?
Are you using the encryption file?

Might even be a softban, due capturing too much in a too short period of time

**Comment by hypixus** [comment]
@dnsBlah I'm such an idiot, I didn't use ENCOUNTER before (facepalm!!!!)
Everything goes well, I'm using only regular pokeballs(are there any other? 0.o)
I did today, I added encounter line before and works like a charm.
Connected GPS module this morning and set it to catch with random chance(no cheating! >:C) every catchable_pokemon with delay 10 minutes and went for 6 hours long shopping. Came back home and lost all pokeballs and got 49 pokemons :')
Never more use function level rewards, so not get ban again.
Thanks for helping me in both cases!

**Comment by dnsBlah** [comment]
what you mean with never use function level awards?
Anyways, 1 = regulair pokeball
2 = great ball
3 = ultra ball
and 4 = master ball

in the encounter you can get a list of which balls you 'should' use for high capture chance

**Comment by hypixus** [comment]
@dnsBlah The only "unusual" thing I've done with this API was calling for level reward twice(accidentaly, experimenting to learn how to use). This is the only api call I've done except get inventory and get player.

**Comment by hypixus** [comment]
BTW. Then where do I get those balls from? Pokestops or purchase?

**Comment by dnsBlah** [comment]
stops :)
