### ISSUE TITLE
Extend Protobuf 

### ISSUE THREAD

**Issue by dmadisetti** [tejado/pokemongo-api-demo#23]
Nicely organized proto files https://github.com/AeonLucid/POGOProtos

**Comment by Simon0x** [comment]
yes really nice proto files. 
still not complete but on a very good way.

**Comment by Simon0x** [comment]
https://github.com/rubenvereecken/pokemongo-protocol

I found this on. Looks really good. Found all Informations i need.
Would prefer that.
Found also informations from gym etc.

That guy is also making his own api https://github.com/rubenvereecken/pokemongo-api

**Comment by dmadisetti** [comment]
Aeon's look more organized, but I haven't compared for content

**Comment by Simon0x** [comment]
Maybe im wrong but i dont find information for gym as example on Aeons's. 
As I see, all the information are on rubenvereecken's files.

**Comment by dmadisetti** [comment]
They're called forts https://github.com/AeonLucid/POGOProtos/search?utf8=%E2%9C%93&q=fort

**Comment by Simon0x** [comment]
ohhh okay nice to know :-) 
now i dont know what i would choose :dancers:

**Comment by tejado** [comment]
Great, thanks! Feel free to add them over PR to the new codebase :) Should be not so complicated anymore.
