### ISSUE TITLE
File "main.py", line 83 except Exception,e :

### ISSUE THREAD

**Issue by bestranger** [tejado/pokemongo-api-demo#26]
Hi, I had a problem. I cant run because it says : 
File "main.py", line 83
except Exception,e :
SyntaxError: Invalid syntax
OR screen - http://prntscr.com/btxp2x

My Command - python main.py -a "google" -u "......gmail.com" -p "......." -l "Location..."

Line 83 : 
        return p_ret
    **except Exception,e:**
        if DEBUG:
            print(e)
        return None

**Comment by tejado** [comment]
Hi, please use python 2.

**Comment by bestranger** [comment]
Hi, thanks. Python 2.7.2 ?

**Comment by bestranger** [comment]
Thank you very much dude, but now it showing, that I havent GPSOAuth, but when before this I had installed. See http://prntscr.com/btxxb5

**Comment by tejado** [comment]
You have to install it separately for python2:
C:\Python27\Scripts\pip.exe install gpsoauth

**Comment by bestranger** [comment]
Thank you, now it working, but cant log in probably for google authenticator.

**Comment by bestranger** [comment]
Yes, now it is working. Thanks.
