### ISSUE TITLE
ERROR: (Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by loretoparisi** [tejado/pokemongo-api-demo#28]
Often getting this error

``` shell
[+] RPC Session Token: xxxxx ...
('Connection aborted.', BadStatusLine("''",))
[-] RPC server offline
```

**Comment by Simon0x** [comment]
This error happen when server has problems....

you did the login with ptc or google?

**Comment by loretoparisi** [comment]
@DerScreever google oauth

**Comment by Simon0x** [comment]
Okay. 
For me this only happen when the server is not reachable.
So no error in script.

**Comment by tejado** [comment]
I will fix it soon ;)

**Comment by loretoparisi** [comment]
@tejado so it was a bug or not?

**Comment by loretoparisi** [comment]
by the way after the pull it seems that the error has been trapped differently

``` shell
HTTPSConnectionPool(host='pgorelease.nianticlabs.com', port=443): Max retries exceeded with url: /plfe/rpc (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10785a850>: Failed to establish a new connection: [Errno 60] Operation timed out',))
[-] RPC server offline
```

**Comment by Simon0x** [comment]
![image](https://cloud.githubusercontent.com/assets/7403387/16902944/49cad7ca-4c6f-11e6-9d49-469d2bb24b09.png)

Problem with the servers.
Only one server online to handle the requests

**Comment by loretoparisi** [comment]
gosh!

**Comment by tejado** [comment]
Yeah, no bug but a bad error handling in the code when the servers are offline which I have to fix :)
