### ISSUE TITLE
can anyone check for whether the search algorithm be improved or not

### ISSUE THREAD

**Issue by MonsterMMORPG** [tejado/pokemongo-api-demo#30]
i am running 3 instances and nothing worthy appears in my city :(

**Comment by Simon0x** [comment]
What searching algorithm. And it does not help if you spam this question everywhere. Not only on this repo i saw

**Comment by MonsterMMORPG** [comment]
@derscreever I have asked each developer once 

The algorithm used to. Move next grid to look which pokemon there

**Comment by Simon0x** [comment]
This is not implemented is this code.
