### ISSUE TITLE
Incorrect results and data missing 

### ISSUE THREAD

**Issue by Cl0v1s** [tejado/pokemongo-api-demo#32]
Hi, I'm currently developing a webApi version of this and since this morning (07/18/2016, it worked well before), i'm having trouble with the data returned by the script. 

In facts, all the data returned are false, and some are missing. This is a sample of what I get by using my account:

```
[!] Your given location: Washington Square, Greenwich, NY 12834, USA  

[!] lat/long/alt: 43.0909305 -73.4989367 0.0  

[!] PTC login for: chaipokoi  

[+] RPC Session Token: TGT-974551-GCMx5k1RW0sqEW ...  

[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/27/rpc  

[+] Login successful  

[+] Username:   

[+] You are playing Pokemon Go since: 1970-01-01 01:00:00  

[+] Poke Storage: 0  

[+] Item Storage: 0
```

As you can see, the field Username is blank, I wasnt born in 1970 and the field POKECOIN and STARDUST are missing.  
Do you think it's a server problem ? A issue caused by my account or the script ?

**Comment by Simon0x** [comment]
i think they updated something at their server.
so maybe our script does not work right now.

**Comment by carloscz** [comment]
For me, sometimes data are correct, seems to be corresponding with server outages in main game app

**Comment by Simon0x** [comment]
just have a look on this. we will see :D

**Comment by Cl0v1s** [comment]
Thanks a lot :D

**Comment by carloscz** [comment]
Yeah, now game is UP for me and data are correct, but not displaying any pokemon in the middle of town (normally is full house) :-/ maybe they modified that part

`[+] You are playing Pokemon Go since: 2016-07-18 10:42:38
[+] Poke Storage: 250
[+] Item Storage: 350
[+] POKECOIN: 0
[+] STARDUST: 100`

**Comment by Simon0x** [comment]
This Repository does not display any pokemon ^^
that is not added in this Repository.

**Comment by Cl0v1s** [comment]
Yeah it works for me too, so it was only a server problem :)

This link has changed for me, it was: 
    https://pgorelease.nianticlabs.com/plfe/27/rpc 
When didnt work and now it's: 
    https://pgorelease.nianticlabs.com/plfe/316/rpc 

It's probably that the server 27 dont have the informations about my account :)

Thanks a lot anyway ! You're making great job ! 👍

**Comment by adrianocr** [comment]
I too am getting: 

> $ python2 main.py -a ptc -u ****\* -p ****\* --location "*******, FL 33054"
> 
> [!] Your given location: *******, FL 33054, USA
> 
> [!] lat/long/alt: ****\* -*****\* 0.0
> 
> [!] PTC login for: ******
> 
> [+] RPC Session Token: TGT-7830932-kSARnJveKC04c ...
> 
> [+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/105/rpc
> 
> [+] Login successful
> 
> [+] Username: *****
> 
> [+] You are playing Pokemon Go since: 2016-07-18 12:39:16
> 
> [+] Poke Storage: 250
> 
> [+] Item Storage: 350
> 
> [+] POKECOIN: 0
> 
> [+] STARDUST: 100

And nothing else.

**Comment by Simon0x** [comment]
this is correct? 
this api does not do anything else.

**Comment by tejado** [comment]
I guess server problem :) Otherwise please use the new codebase, as there are more debug information (if -d is used).
