### ISSUE TITLE
Spoof Pokemon ID

### ISSUE THREAD

**Issue by blackms** [tejado/pokemongo-api-demo#33]
Hello, is it possible to change the Pokemon ID in the server response in order to spawn e different pokemon and capture it?

**Comment by Cl0v1s** [comment]
This script only retrieve data from the server, and cant be used ingame. So i dont think. 

Moreover i dont think cheating is the purpose of this work right ?

**Comment by blackms** [comment]
Well, I'm just curious.

**Comment by Simon0x** [comment]
no cheating is not the purpose if this work.
