### ISSUE TITLE
Loggin Problem?

### ISSUE THREAD

**Issue by tcheguevara** [tejado/pokemongo-api-demo#44]
Is anyone having a problem with the login? Sometimes I login but another times I get 

  File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 844, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.

**Comment by Nostrademous** [comment]
That happens at times when servers are over-loaded. It should resolve itself in a few minutes.

**Comment by tcheguevara** [comment]
Isn't it because of the GOOGLE_LOGIN_ANDROID_ID and GOOGLE_LOGIN_CLIENT_SIG ? I mean that is unchangeable every time, and everyone who is with this API is using the same. I was wondering how do we get a new ID and Sig maybe?

**Comment by tejado** [comment]
Can you please provide the complete stack trace so I can fix the error handling in this area? Thought that I did this already...

You cant change these values. These are static values which are also used by the app, so by anyone else using the Pokemon Go app on a smartphone.

**Comment by Saddness** [comment]
indeed, we need a way to provide GOOGLE_LOGIN_ANDROID_ID, so that NIA cannot trace users and ban them all at once. Can we at least autogenerate it? Same applies to GOOGLE_LOGIN_CLIENT_SIG, it's just a precaution

**Comment by tejado** [comment]
GOOGLE_LOGIN_ANDROID_ID will be send to google and not to NIA. 9774d56d682e549c is also very broadly used, e.g. in emulators.
