### ISSUE TITLE
get_map_objects not returning WildPokemon cells

### ISSUE THREAD

**Issue by Zeromark30** [tejado/pokemongo-api-demo#45]
if i run the old version of code i get

`Fort {
  FortId: "87ab0ef6273d4dc98fa019a18492dafa.16"
  LastModifiedMs: 1468687487635
  Latitude: 
  Longitude: -
  Enabled: true
  FortType: 1
}
WildPokemon {
  LastModifiedMs: 1468977147090
  Latitude: 
  Longitude: -
  SpawnPointId: "88388da5211"
  pokemon {
    PokemonId: 96
  }
  TimeTillHiddenMs: 482034
}`

the new

`"forts": [
            {
              "last_modified_timestamp_ms": 1468687487635, 
              "enabled": true, 
              "longitude": -, 
              "latitude": , 
              "type": 1, 
              "id": "87ab0ef6273d4dc98fa019a18492dafa.16"
            }`

I dont see any WildPokemon in the return. Am i looking in the wrong spot and its not supposed to return willdpokemon?

**Comment by nickblt** [comment]
I'm getting some wild pokemon in the response but fewer than the game or the AHAAAAAAA map sees

**Comment by Zeromark30** [comment]
okay im comparing to a modified AHAAAAAAA as well.

**Comment by Nostrademous** [comment]
I thought I noticed something similar with the protobuf-to-dict usage. Once I switched back to using protobufs directly I have no issues seeing everything. It's possible that module might be encountering something it thinks is end of string.

On the positive side I got catching finally working...

```
Catch Response: 
status: CATCH_SUCCESS
scores {
  activity_type: ACTIVITY_CATCH_POKEMON
  activity_type: ACTIVITY_POKEDEX_ENTRY_NEW
  xp: 100
  xp: 500
  candy: 3
  candy: 0
  stardust: 100
  stardust: 0
}
```

**Comment by Zeromark30** [comment]
Any chance you would commit https://github.com/tejado/pgoapi/issues/42#issuecomment-233759930 this changes and ill fork from you?

**Comment by tejado** [comment]
Thanks a lot! I checked that and the parsing seems to work well.

You can also check that by installing protoc and put the directory path in the environment (Linux: %PATH, Windows: %PATH%). Now execute the pokecli.py as usual plus the --debug argument. Then you can compare the dict with the raw protobuf response (decoded over protoc --decode_raw).
If there is something strange (e.g. it doesnt compare well) then please provide me the output (please remove your authentication/ticket infos first).

Maybe it is an issue with the s2 cell stuff but I will check it.

In regard to #42 I will think how to handle this.

@Nostrademous do you will provide a PR for this? :)

**Comment by tejado** [comment]
So I looked at the PokemonGo-Map code from AHAAAAAAA and saw that they are requesting not only one get_map_objects like my code but several. Feel free to extend my code to fit your purposes, e.g. calling as many Cells as you like.

Btw: It seems that PokemonGo-Map wants to refactor the code with my lib. Maybe if there is really some issue/bug with my code I guess the guys will see it.

**Comment by Zeromark30** [comment]
Probably my fault then. I thought I was looping through  multiple get map object requests.maybe I missed something to update which cell I'm grabbing. Sorry for the extra work.

**Comment by tejado** [comment]
Hmm okay. If you dont find the issue on your side you can send me the code (public or private) and I will check if it is due to pgoapi.

**Comment by nickblt** [comment]
I did some extra digging, it looks like most of the problem was on my side. Chaining api.set_position with api.get_map_objects made everything work.

**Comment by Zeromark30** [comment]
I assume mine will be too. I'm at work but thinking about what I was doing last night I think I was updating position but not cellid

**Comment by nickblt** [comment]
@Zeromark30 I have an example in #52 which just got merged (thanks @tejado ) you can use that as a reference

**Comment by Zeromark30** [comment]
thank you for the example. Looking through my code i was not using the updated positions in the cellid var. sorry for the wasted time @tejado

**Comment by tejado** [comment]
:D no problem!
