### ISSUE TITLE
catch _pokemon give empty response

### ISSUE THREAD

**Issue by setyongr** [tejado/pokemongo-api-demo#46]
I run this code
`api.catch_pokemon(encounter_id=poke['encounter_id'],
                        pokeball=1,
                        normalized_reticle_size=1.950,
                        spawn_point_guid=poke['spawnpoint_id'],
                        hit_pokemon=True,
                        spin_modifier=1,
                        NormalizedHitPosition=1)
`
When i print the response, i get
`"responses": {
    "CATCH_POKEMON": {}
  }
`

**Comment by tejado** [comment]
Hi,

I didnt verified this yet so it is also not listed as supported in the Readme. I will have a look into it. Are you willing to provide me your additional surrounding code (e.g. private per mail or public?)

**Comment by setyongr** [comment]
hi, thanks for replying :)
i just made a small modify to pokecli.py
rest of the code its just searching catchable pokemon throught get_map_objects. But if you want to look all of the code maybe i can send you via email

**Comment by tejado** [comment]
Ah okay, no then it is okay. I will check it myself :)

**Comment by setyongr** [comment]
opps, sorry my bad
its working perfectly, i just forgot to encounter the pokemon

**Comment by ericlewis** [comment]
Could you explain how you made encounter work? I always get status 3

**Comment by ztukaz** [comment]
Could you explain how you made encounter work? I always get status 3 -> +1

**Comment by setyongr** [comment]
@ericlewis @ztukaz  maybe you got softban because you jump to far

**Comment by ztukaz** [comment]
@setyongr it was working perfectly, but for a parameter ( jus myBad )

**Comment by samuelteixeiras** [comment]
@ztukaz what command do you run (params) ?

**Comment by ztukaz** [comment]
You should encounter first the pokemon, than catch
catch_pokemon(encounter_id= encounter_id, pokeball=1, normalized_reticle_size=1.950, spawn_point_guid = spawn_point_guid, hit_pokemon=True, spin_modifier=1, NormalizedHitPosition=1)

Note that Pokeball = 1 refers to pokeball, pokeball = 2 i think it's for mega ball(not tested yet), 3 for master?
