### ISSUE TITLE
Evolving Pokemon

### ISSUE THREAD

**Issue by joshk6656** [tejado/pokemongo-api-demo#48]
On the main page, you mention the RPC request is there for evolving pokemon, could you please show me how to use it?

**Comment by mikeres0** [comment]
+1

**Comment by samuelteixeiras** [comment]
Is it a bad idea create a wiki page for show the usage of the api ?

**Comment by mikeres0** [comment]
@samuelteixeiras It would be a great thing if someone could document each RPC request with the required parameters. I would make a start but I'm in the same boat...

**Comment by tejado** [comment]
No, feel free to do this. But I will also create an examples directory in the repository itself (if you want to be faster than me, create a PR ;)

Im just preparing a bigger update for py3 compatibility and import of all protos of @aeonlucid. So better to wait until this (hope I will push it in an hour or so)

**Comment by samuelteixeiras** [comment]
great @tejado , maybe we can do this using your example files. Good job by the way.

**Comment by HelloKitty** [comment]
I poked around in the old API. I couldn't find a protobuf def for a request that would evolve Pokemon.

Was it missing?

**Comment by jle3** [comment]
@tejado excited for py3 compatibility great work

**Comment by SophisticaSean** [comment]
if you guys checkout https://github.com/tejado/pgoapi/pull/74 you'll see i've added an example call for evolving pokemon in the pokecli.py file

**Comment by tejado** [comment]
https://github.com/tejado/pgoapi/wiki
