### ISSUE TITLE
Support of asynchronous api calls.

### ISSUE THREAD

**Issue by Dr-ZeeD** [tejado/pokemongo-api-demo#49]
I suppose the title says it all ;)

**Comment by tejado** [comment]
What do you have exactly in mind? callback to a given function when the response is returned? Otherwise it could be solved with additional code around the API.

**Comment by Dr-ZeeD** [comment]
At the moment I do not see a way to start asynchronous api calls except for starting multiple processes. It'd be nice if something like grequests could be supported :)

**Comment by RyanHope** [comment]
I could port the backend to use Twisted very easily. That would support async calls. This was actually one of the first thing that I was going to do.

**Comment by tejado** [comment]
With the latest commit, pgoapi should be thread-safe
