### ISSUE TITLE
Google Auth

### ISSUE THREAD

**Issue by LegITdevel** [tejado/pokemongo-api-demo#5]
Add Google authentication method #

**Comment by fremgenc** [comment]
This ingress demo may help. Looks like we need to steal the google cookie.

https://gist.github.com/neonichu/5186336

**Comment by AeonLucid** [comment]
I logged the login request and it gave me this. (This was on android 6.0.1)

Headers:

> POST /auth HTTP/1.1
> device: *****************
> app: com.nianticlabs.pokemongo
> Accept-Encoding: gzip
> User-Agent: GoogleAuth/1.4 (OnePlus3 MMB29M); gzip
> content-length: 521
> content-type: application/x-www-form-urlencoded
> Host: android.clients.google.com
> Connection: Keep-Alive

![pgo_auth](https://cloud.githubusercontent.com/assets/4643257/16849699/005f57c0-49fc-11e6-9c5e-8b2ac9b34da9.png)

There may be another way but I don't know how to figure that out.

**Comment by Mila432** [comment]
working Google Authentication 
https://github.com/Mila432/Pokemon_Go_API

**Comment by tejado** [comment]
Great! Thanks! If you don't mind, you can create a Pull Request to my repo.

**Comment by Mila432** [comment]
It's up to you , people say it's dirty

**Comment by Simon0x** [comment]
https://github.com/tejado/pokemongo-api-demo/pull/17

**Comment by Simon0x** [comment]
This could be closed. merge of #17 done
