### ISSUE TITLE
Use of protoc vs parseFromString

### ISSUE THREAD

**Issue by mattorib** [tejado/pokemongo-api-demo#53]
Just a brief question on your decision with decoding raw protobufs:

Why did you opt to use the `protoc` command line tool in a subprocess instead of sticking to the generated functions, like in the old demo? I don't really know enough about protobufs or the tooling you used to understand the pros and cons by looking over the code. I presume there's a good reason since you are requiring an additional, external dependency.

**Comment by tejado** [comment]
pgoapi use ParseFromString. I added protoc for debugging reasons. So it isnt required and there will be no error if you dont have it.

**Comment by mattorib** [comment]
Ahh, I see. I was always running with debug mode on, so when I saw the message that protoc was not on the PATH I got a bit worried.
