### ISSUE TITLE
Recycle_inventory_item api function

### ISSUE THREAD

**Issue by danil-shatokhin** [tejado/pokemongo-api-demo#54]
recycle_inventory_item is defined in RpcEnum, but don't have a Request\Response realisation in RpcSub. Could something be done with that and who actually made other Requests realisation?

**Comment by danil-shatokhin** [comment]
Sorry, found protos needed in other issue

**Comment by coalwater** [comment]
@xareyx could you link me to the proto you found?
Thanks.

**Comment by tejado** [comment]
@coalwater Please see https://github.com/tejado/pgoapi/issues/97
