### ISSUE TITLE
.proto files missing

### ISSUE THREAD

**Issue by iCyclus** [tejado/pokemongo-api-demo#56]
please update

**Comment by tejado** [comment]
The protos are in https://github.com/tejado/pgoapi/tree/master/pgoapi/protos/POGOProtos
What are you missing?

**Comment by Technolink** [comment]
When you install this code via pip `pip install git+https://github.com/tejado/pgoapi.git`, the protos is not included in the site-packages

**Comment by tejado** [comment]
Oh thanks for the info. I will check it.

**Comment by tejado** [comment]
Should be fixed now. setup.py also installs the proto system-wide now.
