### ISSUE TITLE
Python-Problem

### ISSUE THREAD

**Issue by sadbillo** [tejado/pokemongo-api-demo#6]
Hi, i get the following Error-Message - How can i fix it?

```
$ sudo python main.py -u billo@email.com -p xxxxxxxxx -l Brunswick
[!] Your given location: Brunswick, Germany
[!] lat/long/alt: 52.2688736 10.5267696 0.0
[!] login for: billo@email.com
Traceback (most recent call last):
  File "main.py", line 194, in <module>
    main()
  File "main.py", line 167, in main
    print('[+] RPC Session Token: {} ...'.format(access_token[:25]))
TypeError: 'bool' object has no attribute '__getitem__'
```

Python-Version: 2.7.10

**Comment by tejado** [comment]
Oh thanks for this, forgot to adjust the error handling there.
Seems your username/password are not correct. I will upload a fix and then an you can have a look on the server errors at this step with the -d/--debug argument.

**Comment by sadbillo** [comment]
Thanks for ur Help & Program! 👍

**Comment by tejado** [comment]
Your welcome! Fix is now in the repo.
