### ISSUE TITLE
Would some one explain how APIs like get_map_object work?

### ISSUE THREAD

**Issue by jiaming-jx** [tejado/pokemongo-api-demo#62]
I can see get_map_object was used in demo but cannot find its definition anywhere. Where should I start then?

**Comment by joshk6656** [comment]
You can find the list of the ones you can use here:

https://github.com/tejado/pgoapi/blob/master/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py

scroll down until you see 

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)

those are the implemented ones... Finding the parameters you need to pass is a whole different story.... 

Look here:

https://github.com/tejado/pgoapi/blob/master/pgoapi/protos/POGOProtos/Networking/Requests/Messages_pb2.py

Search for the name of the request you are trying to make and you should see it.

**Comment by jiaming-jx** [comment]
Thank you for your detailed explanation! It's really helpful to me!
