### ISSUE TITLE
Python3 -  ImportError: cannot import name 'protos'

### ISSUE THREAD

**Issue by john-best** [tejado/pokemongo-api-demo#63]
```
Python 3.5.1 (default, Mar  4 2016, 01:39:17)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgoapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/pgoapi/__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/usr/local/lib/python3.5/site-packages/pgoapi/pgoapi.py", line 33, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/usr/local/lib/python3.5/site-packages/pgoapi/rpc_api.py", line 39, in <module>
    from . import protos
ImportError: cannot import name 'protos'
```

I'm on Debian stretch running Python 3.5.1 with protobuf3.0.0b4. I'm not sure if there's something I'm missing or if I have installed the wrong dependency. Thanks!

**Comment by john-best** [comment]
Issue was because I was outside of the directory of pgoapi. For some reason I thought setup.py would have allowed system-wide access to the pgoapi library but it seems I was mistaken.

**Comment by tejado** [comment]
Problem is, that the protos wont be installed yet... stupid installer stuff... will be fixed soon

**Comment by tejado** [comment]
Should be fixed now. setup.py also installs the proto system-wide now.

**Comment by john-best** [comment]
Works on my machine :+1:
