### ISSUE TITLE
Suggestion - Slack Channel 

### ISSUE THREAD

**Issue by mikeres0** [tejado/pokemongo-api-demo#67]
Hello everyone, 

Looking to get some thoughts on setting up a slack channel for this API. I think at this early point in the project it could be of good use to collaborate and share our findings. 

What do you think?

**Comment by ammon-lockwood** [comment]
yes, I would like a place to chat about this.  I'm trying to create a bot for slack if anyone has an example.  I have the slack webhook up, I just need to get the API call to query the location of my work and then send the pokemon it finds to the webhook

**Comment by mikeres0** [comment]
@sumnercreations Here's the link: https://pgoapi.slack.com/

I'll set it up properly later and  update the readme.md. @tejado please email me at mike.resoli@gmail.com and I will add you to the admin asap.

**Comment by ammon-lockwood** [comment]
How do you get into it?  Did you send me an invite so that I can join it?

**Comment by ztukaz** [comment]
Did you send me an invite so that I can join it? -> +1

**Comment by mikeres0** [comment]
I'm waiting on a pull request at the moment, I've updated the readme.md file to include a link to it and also where you need to send an email for an invite. I'm going to set something up tomorrow that'll automate the sign ups. :+1: 

For now email me at mike.resoli@gmail.com

**Comment by elicwhite** [comment]
Gitter wouldn't require an invite and is meant specifically for github repos. Just sayin

**Comment by mikeres0** [comment]
You can now sign up [here](https://pgoapislack.herokuapp.com/)! :8ball:
