### ISSUE TITLE
RpcEnum.proto

### ISSUE THREAD

**Issue by samuelteixeiras** [tejado/pokemongo-api-demo#68]
Hi , you talk about the RpcEnum.proto that have all api calls. I couldn't find this file. 
Maybe create a option to describe the methods , with arg  options like a man page in the linux. 
If you show me a example in the api  I can start this .

**Comment by Cl0v1s** [comment]
I had the same problem, it's here now: https://github.com/tejado/pgoapi/blob/master/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py

**Comment by ryan-shaw** [comment]
@chaipokoi That's not the source .proto file

**Comment by Cl0v1s** [comment]
@ryan-shaw He wants to know all the available api calls, I had the same problem. All the API calls are in this file :)
The .proto file doesnt exist. :/

**Comment by ryan-shaw** [comment]
@chaipokoi Check here - https://github.com/AeonLucid/POGOProtos/tree/master/src/POGOProtos/Networking/Requests/Messages

He moved the project to using those protos.

**Comment by Cl0v1s** [comment]
Wow cool ! Thanks a lot !

**Comment by samuelteixeiras** [comment]
@ryan-shaw , @chaipokoi thanks.
