### ISSUE TITLE
google protobuf error

### ISSUE THREAD

**Issue by ashleyevans** [tejado/pokemongo-api-demo#7]
hey

looking forward to trying this out and contributing. Can I ask which version of python and google protobuf you're using to develop with? I tried to run this on Python 2.7.6 with protobuf 2.5.0 and received errors regarding symbol_database being imported

Thanks

**Comment by tejado** [comment]
Hi,
I'm using python 2.7.12 and protobuf 2.6.1-2 under arch linux.
