### ISSUE TITLE
Printing problem

### ISSUE THREAD

**Issue by ztukaz** [tejado/pokemongo-api-demo#70]
```
bomb = api.catch_pokemon(...)
print ('\n\r{}'.format(pprint.PrettyPrinter(indent=1).pformat(bomb)))
```

results:
`<pgoapi.pgoapi.PGoApi instance at 0x02D41148>`

expected something like
`"responses": { "CATCH_POKEMON": { status: CATCH_SUCCESS } }`

```
Catch Response: 
status: CATCH_FAILED
```

What i am missing to decode the results of the method?

**Comment by Cl0v1s** [comment]
You're actually trying to print the api object (and you never send your request to the server). However you want your response from the server. 
Try to print `bomb.call()`

**Comment by ztukaz** [comment]
Thank you
