### ISSUE TITLE
password?

### ISSUE THREAD

**Issue by fjallstrom** [tejado/pokemongo-api-demo#8]
silly question: username is my pokemon go username, but what is password? my google password?

**Comment by fremgenc** [comment]
Google Authentication does not work yet.

Only Pokemon Trainer Club will work right now.

**Comment by fjallstrom** [comment]
ah, excellent. keep up the good work, i'll try to help with a pr in a bit.

**Comment by Mila432** [comment]
working Google Authentication 
https://github.com/Mila432/Pokemon_Go_API

**Comment by elliottcarlson** [comment]
Working Google Auth in PR
