### ISSUE TITLE
Did Pokemon change something that can not get pokemon location anymore ?

### ISSUE THREAD

**Issue by kevin3747118** [tejado/pokemongo-api-demo#84]
![image](https://cloud.githubusercontent.com/assets/16334296/17060983/eb06c4c6-505e-11e6-814b-a786a9bd7273.png)

I think they modify something to block users get pokemon location

**Comment by ztukaz** [comment]
This happen to me when servers goes down or semi-down ( also in the android app )
Wait till server fixed

**Comment by kevin3747118** [comment]
@ztukaz thanks for your comment ^_^

**Comment by Nostrademous** [comment]
wild pokemons no longer exist

**Comment by kevin3747118** [comment]
@Nostrademous what do u mean  wild pokemons no longer exist ?

**Comment by kevin3747118** [comment]
@ztukaz I believe the ptc server status is online now but still can't get the information what I want !

**Comment by Nostrademous** [comment]
@kevin3747118 if you go on your phone/tablet and play Pokemon Go you will notice all the Pokemon you can see (bottom right hand corner) have 3 feet under them. This has been going on for about 1 week now. 3 feet is the "Nearby Pokemon". "WildPokemon" were 1&2 feet. Niantic got rid of them b/c of people cheating/botting. WildPokemon listed their lat/long so people could cheat easy. Nearby Pokemon list only distance from player, not actual lat/long. Makes it harder.

**Comment by kevin3747118** [comment]
So , we can't get the lat, lon also Pokemon ID via pgoapi right ?

**Comment by Nostrademous** [comment]
Correct, what you have to do is stick with "MapPokemon" (some call them "CatchablePokemon") - these are the ones that appear on you map visible, or you have to write code to use triangulation to find the Nearby Pokemons
