### ISSUE TITLE
Start Gym Battle causes crash

### ISSUE THREAD

**Issue by danil-shatokhin** [tejado/pokemongo-api-demo#88]
api call to start_gym_battle causes response with just status_code=51 and that leads to crash
What does that code correspond to?

Stack:
![image](https://cloud.githubusercontent.com/assets/14920015/17073082/1ba50bb2-5076-11e6-9743-79abbf2f812f.png)

**Comment by danil-shatokhin** [comment]
fort_deploy_pokemon is also kinda interferes with everythin being renamed to "Message" but FortDeployPokemonProto is still Proto instead of Message. This stops rpc from properly loading that

**Comment by tejado** [comment]
The KeyError is fixed in the main branch.
Thanks for the other topic. I will update the protos soon :)

**Comment by tejado** [comment]
Protos are updated :)
