### ISSUE TITLE
Encounter_id missing in Fort.LureInfo

### ISSUE THREAD

**Issue by rvanvenetie** [tejado/pokemongo-api-demo#89]
I'm trying to get disk_encouter to work, but encouter_id is missing from fort.lureinfo. I've tried generating new protos from POGOProtos, but then somehow the get_map_objects breaks?

**Comment by IgnasKancleris** [comment]
Found a fix for get_map_objects with the new protos. In the new protos the location coordinates in the RequestEnvelope are floats instead of bytes, so this code incorrectly double converts the coordinates. Change the getPosition to return self._posf and it should work.

**Comment by rvanvenetie** [comment]
Awesome, thanks!

**Comment by glenncampioni** [comment]
Added it with PR #117

**Comment by tejado** [comment]
Should be fixed now :)
