### ISSUE TITLE
client secret

### ISSUE THREAD

**Issue by pxue** [tejado/pokemongo-api-demo#9]
https://github.com/tejado/pokemongo-api-demo/blob/master/main.py#L138

you should parameterize this. worst case I can hijack everyone who's using this' session.

you should capture the initial oauth exchange from your app to niantic.

**Comment by tejado** [comment]
Like this? :) https://github.com/tejado/pokemongo-api-demo/commit/d0642a91926dacdd8279d31a3782b2d1e37eb42c

**Comment by ghost** [comment]
Client secret authorizes the client/software to use the api to create access tokens. Everyone using the pokemon go app has the same key. No need to parameterize it. There is no way you can hijack anyone's session using this.

**Comment by tejado** [comment]
Yes, I thought the same. But wasn't sure anymore due to different opinions and also pxue comment.
Thanks!

**Comment by pxue** [comment]
@wiez you're right that client secret is an authorization method, and right about everyone uses the same key. however, in normal circumstances the client secret is server side and hidden from the users, never in the client. For example, github its self says client [secret should never be shared](https://developer.github.com/v3/oauth/) and [RFC6819](https://tools.ietf.org/html/rfc6819#section-4.1.1) touches very briefly about the dangers of exposed client secret.

Either way, this is a demo, just wanted to let people know :)

**Comment by Mila432** [comment]
@pxue you are wrong , if the dev uses a static key , nobody gets another and i have seen like 50+ apps out there that does the same
