### ISSUE TITLE
Pointless code

### ISSUE THREAD

**Issue by SquishyStrawberry** [tejado/pokemongo-api-demo#91]
While this isn't really an issue, I'm sure it can be considered a "speed concern" and in general it'd be a good idea to refactor it.

In the file [utilities.py](https://github.com/tejado/pgoapi/blob/master/pgoapi/utilities.py#L38-L44), in lines 38 to 44, there is this code snippet:

``` python
def to_camel_case(value):
  def camelcase():
    while True:
      yield str.capitalize

  c = camelcase()
  return "".join(next(c)(x) if x else '_' for x in value.split("_"))
```

While this code _works_, it's very unefficient. This can be attributed to using a pointless generator function.

A better solution would be this code snippet:

``` python
def to_camel_case(value):
    return "".join(x.capitalize() if x else "_" for x in value.split("_"))
```

I hope you take care of this as soon as possible, as it's a very easy issue to fix.

If possible, I'd like to understand just what **went into making this snippet**, seeing as it's a very convuluted way of doing things which I just don't understand.

---

Another issue might be in the naming, seeing as this is the output I get in iPython:

``` python
In [1]: def to_camel_case(value):
   ...:         return "".join(x.capitalize() if x else "_" for x in value.split("_"))
   ...: 

In [2]: to_camel_case("to_camel_case")
Out[2]: 'ToCamelCase'
```

This kind of case is called `PascalCase`, which may look similiar to `camelCase`, but is characterized by having the first character of the word capitalized too unlike `camelCase`.

Possible solutions to the **this** issue:
- Rename the function to `to_pascal_case`
- Replace the function with this function:

``` python
def to_camel_case(value):
    pascal_case = "".join(x.capitalize() if x else "_" for x in value.split("_"))
    return pascal_case[0].lower() + pascal_case[1:]
```

**Comment by ghost** [comment]
Since the transformation wanted is `abc_def → Abc_Def → AbcDef`, the following should be easier to use

``` python
return "".join(x.capitalize() for x in value.split("_"))
```

unless there are cases when `_` is wanted in the output

**Comment by aldanor** [comment]
Or use [`inflection`](https://inflection.readthedocs.io/en/latest/) and don't reinvent the wheel 😄 

``` python
import inflection

inflection.camelize(value)
```

**Comment by SquishyStrawberry** [comment]
@Socialery While I do believe that your solution is a better one, I'm unsure of how the function is actually used within the source so I just wanted to keep the "original behavior".

@aldanor Some people are against dependencies for something _so small_

**Comment by tejado** [comment]
Thanks a lot :) I will check for this tomorrow as I dont have enough time today. But I really appreciate it.
I will also explain the stuff about my code ;)

**Comment by SquishyStrawberry** [comment]
Alright, awesome @tejado!

**Comment by tejado** [comment]
Thanks all! I like such contributions as I learn from it ;) To be honest, I have the code from [here](http://stackoverflow.com/a/4306777). I just wanted to get my rewrite functional done, so I didnt take care of such topics. Now is the time to clean them up ;)
I also didn't know, that it is named pascalcase (or UpperCamelCase by wikipedia). Good to know. I will consider a renaming,
