### ISSUE TITLE
pgoapi slack invite limit reached

### ISSUE THREAD

**Issue by wtfbbqhax** [tejado/pokemongo-api-demo#94]
FYI, https://pgoapislack.herokuapp.com/ is returning _"Failed! invite_limit_reached"_.

**Comment by tejado** [comment]
@mikeres0 ? :) Do you know how to resolve this?

**Comment by mikeres0** [comment]
I'll look into this now... However I've just done some reading about this and I think I'll have to contact slack to get them to up the limit. I believe we've currently maxed out at 100 invites. Even if we cancel the pending invites it does not allow any more invites to be sent. I'll keep you posted.

**Comment by mikeres0** [comment]
Issue has been solved by Slack :+1: this can be closed.

**Comment by tejado** [comment]
Thanks mikeres0
