### ISSUE TITLE
Set POGOProtos as a git submodule

### ISSUE THREAD

**Issue by frankhouzz** [tejado/pokemongo-api-demo#95]
POGOProtos has some updates recently which fixed some bug about incubator and etc.
So I suggest to make it as a git submodule so we can easily keep update with it.

**Comment by tejado** [comment]
Yeah, I would like to do that but the problem is, that I need the compiled protos which are not in the repo. And the users of pgoapi should not be required to install protoc. 

I will update the protos soon, at latest when I release pgoapi 1.2.0.

**Comment by frankhouzz** [comment]
I tried that. 
Only thing you need to change is to remove the f2i function completely since the GPS coordinate is change to float.
