### ISSUE TITLE
Link to pogobuf (Node.js library/port)

### ISSUE THREAD

**Issue by cyraxx** [tejado/pokemongo-api-demo#96]
Hi!

I just released [pogobuf](https://github.com/cyraxx/pogobuf), a Node.js Pokémon Go client library. It's not a direct port of pgoapi but very much based on it.

I am aware that there is already another Node.js port but I didn't like some of the design decisions (mostly the fact that seems to be focused on botting/farming instead of being a client library). Not that I'm trying to discourage their work, if that's what works best for them that's fine.

Anyway, pogobuf is still a little WIP and rough around the edges but it works fine and <sup>theoretically</sup> supports all known API calls, so I thought you might want to link to it in the README.

**Comment by tejado** [comment]
Added
