### ISSUE TITLE
Ok, where do you find methods to call?

### ISSUE THREAD

**Issue by oinquer** [tejado/pokemongo-api-demo#97]
I have been scouring over the github for pieces here and there, how are you guys getting the methods to call from the api?
how do you know that exists an api.use_item_egg_incubator ? or that exists api.get_map_objects

im sorry if i sound dumb normally i follow some documentation but i cant find anything similar.

**Comment by kehphin** [comment]
From the README: "All (known) RPC calls against the original Pokemon Go servers are listed in the RequestMethod Enum in the pgoapi/protos/RpcEnum.proto file."

**Comment by tejado** [comment]
pgoapi uses a way of dynamic methods. So you can basically use every method on the api object, like api.method_does_not_exist(). The code knows, which methods are existing, by checking the enum object of the protos. The readme is not up to date (will update that now), so the new enum is RequestType inside https://github.com/tejado/pgoapi/blob/master/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py 
So this has all Pokemon Go API calls included and the code knows what api call exist and which not.

**Comment by oinquer** [comment]
@kehphin thanks, but i did read that, the file is not there anymore.

@tejado Thanks! now i see them all, that will be very helpful.

**Comment by tejado** [comment]
Your welcome :)
