### ISSUE TITLE
plural of pokemon is pokemon

### ISSUE THREAD

**Issue by tcmaps** [tejado/pokemongo-api-demo#99]
just noticed some function in the api are called xxx_pokemonS, like wild_pokemons

well thats ultimate nitpicking but just sayin... ;)

**Comment by tejado** [comment]
@AeonLucid maybe you can comment on this? :)

**Comment by nborrmann** [comment]
I'm sure he knows and did it on purpose. How else are you going to write
`for pokemon in pokemons:`

**Comment by NorthIsUp** [comment]
I've seen other places refer to them as "mon" so `for mon in pokemon`

**Comment by tejado** [comment]
So at least I won't change this as I'm using AeonLucid protos :)
